Сreated CRC cards
livace/rpn-calculator pull request #7
Opened 2021-03-16 16:11 UTC by asokol123

2021-03-21 12:25 UTC, nvamelichev requested changes

2021-03-21 12:25 UTC, nvamelichev commented on crc.md
> +* `EvaluatePostfixExpression`. Принимает последовательность токенов в постфиксной записи, вычисляет, возвращает результат его вычисления.
* Evaluate*Expression - весьма низкоуровневые методы. А класс Calculator мне видится как **Фасад**, который все компоненты системы соединяет воедино и предоставляет пользователю простой, высокоуровневой интерфейс. Думаю, эти методы относятся к какому-то другому классу.
* Подумайте, как поменяется класс Calculator, если придётся поддержать ещё один синтаксис - префиксную запись (`+ 1 3 = 4`). В текущем варианте, вам придётся добавить метод `Evaluate**Infix**Expression`, хотя логика работы калькулятора останется точно такой же. => Кмк тут просится применить паттерн "Стратегия": выделить вычисление значения выражения в интерфейс "вычислителя", у которого будет две реализации (инфиксная и постфиксная), и в зависимости от типа нотации вызывать в Calculator'е нужный "вычислитель". Может быть, даже, enum'ка "тип нотации" сама и будет реализовывать интерфейс "вычислителя": в Java enum'ки умные, они классы и могут реализовывать интерфейсы :-)

2021-03-21 12:25 UTC, nvamelichev commented on crc.md
> +* `GetCoundOfArguments`. Возвращает число параметров, которое принимает операция.
опечатка: GetCoun**t**OfArguments. А даже лучше - `GetArgumentCount`

2021-03-21 12:25 UTC, nvamelichev commented on crc.md
> +Интерфейс для арифметической операции.
Я бы в методы ещё добавил получение имени операции, раз оно должно быть уникальным для Calculator.RegisterOperation()

2021-03-21 12:25 UTC, nvamelichev commented on crc.md
> +* `Tokenize`. Принимает строку, возвращает последовательность токенов.
Токены - имеются в виду String'и, char'ы, экземпляры какого-то класса?

2021-03-21 12:25 UTC, nvamelichev commented on crc.md
> +* `Start`. Запускает `REPL`.
Судя по наличию только одного метода, ваш метод Start() - блокирующий и не возвращает управление основной программе, пока пользователь не выйдет из REPL'а. Это неочевидное поведение, которое стоит документировать - скажем, в JDK метод Thread.start() запускает поток и сразу возвращает управление. Ну и название методу стоит придумать какое-то более говорящее, скажем, "EnterLoop" - войти в цикл, уже намекает на то, что управление передаётся REPL'у до тех пор, пока пользователь не скажет "всё, надоело вычислять :-)"

И обязательно предусмотрите команду выхода из REPL'а. Пользователи, вынужденные завершать программу по Ctrl+C (Ctrl+Break на Windows) или даже `kill -9 <...>`, обычно бывают очень недовольны :-)

2021-03-21 12:25 UTC, nvamelichev commented on crc.md
> +* `RegisterOperation`.Принимает на вход имя операции, количество параметров и `Callable`. Создает новую операцию и сохраняет под данным именем. Бросает `IllegalArgumentException` если имя уже использ
> принимает имя, количество параметров и `Callable`... 

а давайте сразу `Operation` будет принимать?
все арифметические операции - чистые функции без побочных эффектов и состояния, так что экземпляры `Operation` можно просто создать один раз и юзать многократно :-)

2021-03-25 23:52 UTC, asokol123 commented on crc.md
> +Интерфейс для арифметической операции.
Но потенциально у одной функции может быть много имен. Например `**` и `^` можно обе назначить на степень.

2021-03-26 07:41 UTC, nvamelichev commented on crc.md
> +Интерфейс для арифметической операции.
А, у вас имя функции совпадает с тем, как она представлена в выражении? Окей :-)

2021-03-26 07:52 UTC, nvamelichev requested changes
Остались буквально минорные изменения)

2021-03-26 07:52 UTC, nvamelichev commented on crc.md
> +`Enum`, содержащий разные нотации.
Про то, что нотации вы реализуете енумкой, в проектной документации можно не писать. Это уже деталь-деталь реализации. Тогда в доках Notation\NotationInterface можно будет объединить в один класс, потому что концептуально они представляют одно и то же - нотацию арифметических выражений

2021-03-27 21:42 UTC, nvamelichev approved these changes

2021-03-27 21:43 UTC, nvamelichev commented
CRC-карточки одобрены

2021-03-27 21:43 UTC, merged